#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
set_time_limit(0);
ini_set('memory_limit', '-1');

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require('web/Yii.php');
require(__DIR__ . '/config/bootstrap.php');

$config = require(__DIR__ . '/config/console.php');

$application = new ConsoleApplication($config);
$exitCode = $application->run();
exit($exitCode);
